WhosOnFirstWeb/Controllers/CoachController.cs
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using WhosOnFirst.Data.Sql.Controllers;
using WhosOnFirst.Data.Sql.Models;
using WhosOnFirstWeb.Models;
using static WhosOnFirstWeb.Actions.PlayerActions;

namespace WhosOnFirstWeb.Controllers
{
    public class CoachController : Controller
    {
        #region CoachIndex
        public ActionResult CoachIndex()
        {
            var userModel = Session["userModel"] as UserModel;
            var coachModel = new CoachModel();
            coachModel.UserModel = userModel;

            return View(coachModel);
        }


        #endregion

        #region AddTeam
        [HttpPost]
        public async Task<ActionResult> AddTeam(CoachModel coachModel)
        {

            var teamsManager = new TeamsManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var teamExists = await teamsManager.ExistsAsync(coachModel.TeamName);
            if (!teamExists)
                teamsManager.AddAsync(coachModel.TeamName);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = new Person();
            var userModel = Session["userModel"] as UserModel;
            person.PersonId = userModel.PersonId;
            person.FirstName = userModel.FirstName;
            person.LastName = userModel.LastName;
            person.PhoneNumber = userModel.PhoneNumber;
            person.EMail = userModel.EMail;
            person.IsPlayer = userModel.IsPlayer;
            person.IsCoach = userModel.IsCoach;
            person.IsValid = userModel.IsValid;
            person.IsAdmin = userModel.IsAdmin;
            var team = await teamsManager.RetrieveAsync(coachModel.TeamName);
            person.TeamId = team.TeamsId;
            personManager.Update(person);
            userModel.TeamId = team.TeamsId;
            Session["userModel"] = userModel;

            return View(coachModel);
        }
        #endregion

        #region ViewTeamPlayers
        public async Task<ActionResult> ViewTeamPlayers(int Id)
        {
            var players = await GetPlayersInTeamAsync(Id);

            return View(players);
        }
        #endregion

        #region ViewAllTeams
        public async Task<ActionResult> ViewAllTeams()
        {
            var userModel = Session["userModel"] as UserModel;
            var teamsManager = new TeamsManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var teams = await teamsManager.GetAllAsync();

            ViewBag.TeamStatus = userModel.TeamId;

            return View(teams);
        }
        #endregion

        #region RemoveTeam
        public ActionResult RemoveTeam()
        {
            var userModel = Session["userModel"] as UserModel;
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = new Person();
            person.PersonId = userModel.PersonId;
            person.FirstName = userModel.FirstName;
            person.LastName = userModel.LastName;
            person.PhoneNumber = userModel.PhoneNumber;
            person.EMail = userModel.EMail;
            person.IsPlayer = userModel.IsPlayer;
            person.IsCoach = userModel.IsCoach;
            person.IsValid = userModel.IsValid;
            person.IsAdmin = userModel.IsAdmin;
            person.TeamId = 0;
            personManager.Update(person);
            userModel.TeamId = 0;
            Session["userModel"] = userModel;

            return RedirectToAction("CoachIndex");
        }

        #endregion

        #region EditPlayer
        public async Task<ActionResult> EditPlayer(int Id)
        {
            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var playerModel = new Players();
            var player = new PlayersModel();
            var person = new Person();
            playerModel = await playerManager.RetrieveAsync(Id);
            player.PlayerId = Id;
            player.PersonId = playerModel.PersonId;
            player.PositionRequested = playerModel.PositionRequested;
            player.TeamRequested = playerModel.TeamRequested;
            player.JerseyNumber = playerModel.JerseyNumber;
            player.Note = playerModel.Note;
            player.IsPitcher = playerModel.IsPitcher;
            person = await personManager.RetrieveAsync(playerModel.PersonId);
            player.FirstName = person.FirstName;
            player.LastName = person.LastName;
            player.PhoneNumber = person.PhoneNumber;
            player.EMail = person.EMail;
            player.IsPlayer = person.IsPlayer;
            player.IsCoach = person.IsCoach;
            player.IsValid = person.IsValid;
            player.IsAdmin = person.IsAdmin;
            player.TeamId = person.TeamId;

            return View(player);
        }

        [HttpPost]
        public ActionResult EditPlayer(PlayersModel editedPlayers)
        {

            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var playerModel = new Players();
            var person = new Person();
            //playerModel = playerManager.Retrieve(editedPlayers.PersonId);
            playerModel.PlayerId = editedPlayers.PlayerId;
            playerModel.PositionRequested = editedPlayers.PositionRequested;
            playerModel.TeamRequested = editedPlayers.TeamRequested;
            playerModel.JerseyNumber = editedPlayers.JerseyNumber;
            playerModel.Note = editedPlayers.Note;
            playerModel.IsPitcher = editedPlayers.IsPitcher;
            playerModel.PersonId = editedPlayers.PersonId;
            playerManager.Update(playerModel);
            person.PersonId = editedPlayers.PersonId;
            person.FirstName = editedPlayers.FirstName;
            person.LastName = editedPlayers.LastName;
            person.PhoneNumber = editedPlayers.PhoneNumber;
            person.EMail = editedPlayers.EMail;
            person.IsPlayer = editedPlayers.IsPlayer;
            person.IsCoach = editedPlayers.IsCoach;
            person.IsValid = editedPlayers.IsValid;
            person.IsAdmin = editedPlayers.IsAdmin;
            person.TeamId = editedPlayers.TeamId;
            personManager.Update(person);

            return RedirectToAction("ViewTeamPlayers");
        }
        #endregion

        #region ViewAvailablePeople
        public async Task<ActionResult> ViewAvailablePeople()
        {
            var players = await GetPlayersInTeamAsync(0);

            return View(players);
        }
        #endregion

        #region AddPlayer
        public ActionResult AddPlayer(int Id)
        {
            var userModel = Session["userModel"] as UserModel;
            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var player = new Players();
            player = playerManager.Retrieve(Id);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = new Person();
            person = personManager.Retrieve(player.PersonId);
            person.TeamId = userModel.TeamId;
            personManager.Update(person);

            return RedirectToAction("ViewAvailablePeople");
        }
        #endregion

        #region RemovePlayerFromTeam
        public ActionResult RemovePlayerFromTeam(int Id)
        {
            var userModel = Session["userModel"] as UserModel;
            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var player = new Players();
            player = playerManager.Retrieve(Id);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = new Person();
            person = personManager.Retrieve(player.PersonId);
            var teamId = person.TeamId;
            person.TeamId = 0;
            personManager.Update(person);

            return RedirectToAction("ViewTeamPlayers", new { id = teamId });
        }
        #endregion

        #region CoachTeam
        public ActionResult CoachTeam(int Id)
        {
            var userModel = Session["userModel"] as UserModel;
            userModel.TeamId = Id;
            Session["userModel"] = userModel;
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = personManager.Retrieve(userModel.PersonId);
            person.TeamId = Id;
            personManager.Update(person);

            return RedirectToAction("ViewAllTeams");
        }
        #endregion

        #region LeaveTeam
        public ActionResult LeaveTeam()
        {
            var userModel = Session["userModel"] as UserModel;
            userModel.TeamId = 0;
            Session["userModel"] = userModel;
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var person = personManager.Retrieve(userModel.PersonId);
            person.TeamId = 0;
            personManager.Update(person);

            return RedirectToAction("ViewAllTeams");
        }
        #endregion



    }
}

WhosOnFirstWeb/Views/Coach/AddPlayer.cshtml
@{
    ViewBag.Title = "AddPlayer";
}

<h2>AddPlayer</h2>

WhosOnFirstWeb/Views/Coach/AddTeam.cshtml
@model WhosOnFirstWeb.Models.CoachModel
@{
    ViewBag.Title = "AddTeam";
}

<h2>Team Successfully Added</h2><br/>
<h2>You are now the coach of @Model.TeamName</h2><br/>
<p>You will be redirected in 3 seconds</p>
<script>
        var timer = setTimeout(function() {
            window.location.href = '@Url.Action("CoachIndex","Coach")';
            },
            3000);
</script>

WhosOnFirstWeb/Views/Coach/CoachIndex.cshtml
@model WhosOnFirstWeb.Models.CoachModel
@{
    ViewBag.Title = "CoachIndex";
}

<div class="form-group" , style="float: left; margin-left: 10px">
    <h1>Welcome Coach @Model.UserModel.LastName!</h1>
</div>
<div class="form-group" , style="float: left; margin-left: 10px">
    <button class="btn btn-link btn-sm" style="margin-bottom: 5px;" onclick="location.href = '@Url.Action("EditUserProfile", "Home", new {Id = @Model.UserModel.PersonId})'">Edit Profile</button>
</div>
<div style="clear: both;"></div>
<br />

@if (!Model.UserModel.IsCoach || !Model.UserModel.IsValid)
{
    <label>You are not an authorized user.</label>
        <p>You will be redirected in 3 seconds</p>
        <script type="text/javascript">
            var timer = setTimeout(function() {
                window.location.href = '@Url.Action("Index", "Home")';
            },3000);
        </script>
}
else
{
    <div class="form-group" , style="float: left;">

        <form action="~/Coach/ViewAllTeams">
            <button class="btn btn-primary" style="margin-bottom: 5px;">View Teams</button>
        </form>
        @{
            if (Model.UserModel.TeamId == 0)
            {

                using (Html.BeginForm("AddTeam", "Coach", FormMethod.Post))
                {
                    @Html.Label("Team Name")
                    @Html.TextBoxFor(m => m.TeamName, new
                   {
                       @class = "form-control",
                       autofocus = "autofocus",
                       placeholder = "Don't use prefixes like THE"
                   })
                    <button id="addTeamButton" class="btn btn-success" style="margin-top: 10px">Add a Team</button>
                }
            }
            else
            {
                <form action="~/Coach/RemoveTeam">
                    <button class="btn btn-danger" style="margin-bottom: 5px;" >Remove Team</button>
                </form>
            }
        }

    </div>


        <div class="form-group" , style="float: left; margin-left: 10px">
            <div>
                <button class="btn btn-primary" style="margin-bottom: 5px;" onclick="location.href = '@Url.Action("ViewTeamPlayers", "Coach", new {Id = @Model.UserModel.TeamId})'">View Players</button>
            </div>

            <form action="~/Coach/ViewAvailablePeople">
                <button class="btn btn-success" style="margin-bottom: 5px;">Available Players</button>
            </form>

            @*<form action="~/Home/Index">
                <button class="btn btn-danger" style="margin-bottom: 5px;" onclick="location.href = '@Url.Action("RemovePlayerFromTeam", "Coach", new {Id = @Model.UserModel.PersonId})'">Remove a Player</button>
            </form>*@
        </div>

        <div style="clear: both;"></div>

            }

WhosOnFirstWeb/Views/Coach/CoachTeam.cshtml
@{
    ViewBag.Title = "CoachTeam";
}

<h2>CoachTeam</h2>

WhosOnFirstWeb/Views/Coach/EditPlayer.cshtml
@model WhosOnFirstWeb.Models.PlayersModel
@{
    ViewBag.Title = "EditPlayer";
}
<h2>Edit User</h2>
<br />
<ul>
    <li>
        @using (Html.BeginForm("EditPlayer", "Coach", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.PersonId, new { @Value = Model.PersonId })
            @Html.HiddenFor(m => m.PlayerId, new { @Value = Model.PlayerId })
            @Html.HiddenFor(m => m.IsPlayer, new { @Value = Model.IsPlayer })
            @Html.HiddenFor(m => m.IsCoach, new { @Value = Model.IsCoach })
            @Html.HiddenFor(m => m.IsAdmin, new { @Value = Model.IsAdmin })
            @Html.HiddenFor(m => m.IsValid, new { @Value = Model.IsValid })
            @Html.HiddenFor(m => m.IsPitcher, new { @Value = Model.IsPitcher })
            @Html.HiddenFor(m => m.TeamId, new { @Value = Model.TeamId })

            <div class="form-group">
                @Html.Label("First Name")
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.FirstName })
            </div>
            <div class="form-group">
                @Html.Label("Last Name")
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.LastName })
            </div>
            <div class="form-group">
                @Html.Label("E-mail Address")
                @Html.TextBoxFor(m => m.EMail, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.EMail })
            </div>
            <div class="form-group">
                @Html.Label("Phone Number")
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.PhoneNumber })
            </div>
            <div class="form-group">
                @Html.Label("Position Requested")
                @Html.TextBoxFor(m => m.PositionRequested, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.PositionRequested })
            </div>
            <div class="form-group">
                @Html.Label("Team Requested")
                @Html.TextBoxFor(m => m.TeamRequested, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.TeamRequested })
            </div>
            <div class="form-group">
                @Html.Label("Note")
                @Html.TextAreaFor(m => m.Note, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.Note, rows = "5", cols = "20" })
            </div>

            <br />
            <input type="submit" class="btn btn-primary" name="Submit" />
        }
    </li>
</ul>

WhosOnFirstWeb/Views/Coach/ViewAllTeams.cshtml
@{
    ViewBag.Title = "ViewAllTeams";
}

<h1>Team List</h1>
<br />
<div>
    @foreach (var teams in Model)
    {
        <div class="form-group" , style="float: left;">
            <div>
                <label>@teams.TeamName</label>
            </div>
        </div>
        <div class="form-group" , style="float: left;">
            @if (ViewBag.TeamStatus == 0)
            {
                <button class="btn btn-primary btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("CoachTeam","Coach", new {Id = @teams.TeamsId})'">Coach Team</button>
            }
            else if (teams.TeamsId == ViewBag.TeamStatus)
            {
                <form action="~/Coach/LeaveTeam">
                    <button class="btn btn-danger btn-sm" style="margin-left: 20px">Leave Team</button>
                </form>
            }
        </div>
        <div style="clear: both;"></div>
    }
    <br />
</div>
<form action="~/Coach/CoachIndex">
    <button class="btn btn-success">Back</button>
</form>

WhosOnFirstWeb/Views/Coach/ViewAvailablePeople.cshtml
@{
    ViewBag.Title = "ViewAvailablePeople";
}

<h1>Available Players</h1>
<br/>
<div>
    @foreach (var player in Model)
    {
        <div class="form-group" , style="float: left;">
            <div>
                <label style="font-size: 20px">@player.FirstName @player.LastName</label>
                <label>&nbsp;&nbsp;Phone Number:  @player.PhoneNumber</label>
                <label>&nbsp;&nbsp;e-mail:  @player.EMail</label>
            </div>
            <div>
                <label>Position Requested:  @player.PositionRequested</label>
                <label>&nbsp;&nbsp;Team Requested:  @player.TeamRequested</label>
            </div>
            <div>

                <label>Note:  @player.Note</label>
            </div>
        </div>
        <div class="form-group" , style="float: left;">
            <button class="btn btn-primary btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("EditPlayer","Coach", new {Id = @player.PersonId})'">Edit</button>
            <button class="btn btn-warning btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("AddPlayer","Coach", new {Id = @player.PlayerId})'">Add To Team</button>
        </div>
        <div style="clear: both;"></div>
    }
</div>
<div style="clear: both;"></div>
<br />

<form action="~/Coach/CoachIndex">
    <button class="btn btn-primary">Back</button>
</form>

WhosOnFirstWeb/Views/Coach/ViewTeamPlayers.cshtml
@{
    ViewBag.Title = "ViewTeamPlayers";
}

<h1>Players on team</h1>
<br />
<div>
    @foreach (var player in Model)
    {
        <div class="form-group" , style="float: left;">
            <div>
                <label style="font-size: 20px">@player.FirstName @player.LastName</label>
                <label>&nbsp;&nbsp;Phone Number:  @player.PhoneNumber</label>
                <label>&nbsp;&nbsp;e-mail:  @player.EMail</label>
                <label>&nbsp;&nbsp;Jersey Number:  @player.JerseyNumber</label>
            </div>
            <div>
                <label>Position Requested:  @player.PositionRequested</label>
                <label>&nbsp;&nbsp;Team Requested:  @player.TeamRequested</label>
            </div>
            <div>

                <label>Note:  @player.Note</label>
            </div>
        </div>
        <div class="form-group" , style="float: left;">
            <button class="btn btn-primary btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("EditPlayer","Coach", new {Id = @player.PersonId})'">Edit</button>
            <button class="btn btn-danger btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("RemovePlayerFromTeam","Coach", new {Id = @player.PlayerId})'">Remove</button>
        </div>
        <div style="clear: both;"></div>
    }
</div>
<div style="clear: both;"></div>
<br />

<form action="~/Coach/CoachIndex">
    <button class="btn btn-primary">Back</button>
</form>