WhosOnFirstWeb/Controllers/PlayerController.cs
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using WhosOnFirst.Data.Sql.Controllers;
using WhosOnFirst.Data.Sql.Models;
using WhosOnFirstWeb.Models;
using static WhosOnFirstWeb.Actions.PlayerActions;

namespace WhosOnFirstWeb.Controllers
{
    public class PlayerController : Controller
    {
        #region PlayerIndex
        public async Task<ActionResult> PlayerIndex()
        {
            var userModel = Session["userModel"] as UserModel;
            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var playerModel = new Players();
            var player = new PlayersModel();
            var person = new Person();
            player.UserModel = userModel;
            playerModel = await playerManager.RetrieveAsync(player.UserModel.PersonId);
            player.PlayerId = player.UserModel.PersonId;
            player.PersonId = playerModel.PersonId;
            player.PositionRequested = playerModel.PositionRequested;
            player.TeamRequested = playerModel.TeamRequested;
            player.JerseyNumber = playerModel.JerseyNumber;
            player.Note = playerModel.Note;
            player.IsPitcher = playerModel.IsPitcher;
            person = await personManager.RetrieveAsync(playerModel.PersonId);
            player.FirstName = person.FirstName;
            player.LastName = person.LastName;
            player.PhoneNumber = person.PhoneNumber;
            player.EMail = person.EMail;
            player.IsPlayer = person.IsPlayer;
            player.IsCoach = person.IsCoach;
            player.IsValid = person.IsValid;
            player.IsAdmin = person.IsAdmin;
            player.TeamId = person.TeamId;

            return View(player);
        }

        #endregion

        #region EditPlayer
        public async Task<ActionResult> EditPlayer()
        {
            var userModel = Session["userModel"] as UserModel;
            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var playerModel = new Players();
            var player = new PlayersModel();
            var person = new Person();
            player.UserModel = userModel;
            playerModel = await playerManager.RetrieveAsync(player.UserModel.PersonId);
            player.PlayerId = playerModel.PlayerId;
            player.PersonId = playerModel.PersonId;
            player.PositionRequested = playerModel.PositionRequested;
            player.TeamRequested = playerModel.TeamRequested;
            player.JerseyNumber = playerModel.JerseyNumber;
            player.Note = playerModel.Note;
            player.IsPitcher = playerModel.IsPitcher;
            person = await personManager.RetrieveAsync(playerModel.PersonId);
            player.FirstName = person.FirstName;
            player.LastName = person.LastName;
            player.PhoneNumber = person.PhoneNumber;
            player.EMail = person.EMail;
            player.IsPlayer = person.IsPlayer;
            player.IsCoach = person.IsCoach;
            player.IsValid = person.IsValid;
            player.IsAdmin = person.IsAdmin;
            player.TeamId = person.TeamId;

            return View(player);
        }

        [HttpPost]
        public ActionResult EditPlayer(PlayersModel editedPlayers)
        {

            var playerManager = new PlayerManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var personManager = new PersonManager(ConfigurationManager.ConnectionStrings["WhosOnFirstDb"].ConnectionString);
            var playerModel = new Players();
            var person = new Person();
            //playerModel = playerManager.Retrieve(editedPlayers.PersonId);
            playerModel.PlayerId = editedPlayers.PlayerId;
            playerModel.PositionRequested = editedPlayers.PositionRequested;
            playerModel.TeamRequested = editedPlayers.TeamRequested;
            playerModel.JerseyNumber = editedPlayers.JerseyNumber;
            playerModel.Note = editedPlayers.Note;
            playerModel.IsPitcher = editedPlayers.IsPitcher;
            playerModel.PersonId = editedPlayers.PersonId;
            playerManager.Update(playerModel);
            person.PersonId = editedPlayers.PersonId;
            person.FirstName = editedPlayers.FirstName;
            person.LastName = editedPlayers.LastName;
            person.PhoneNumber = editedPlayers.PhoneNumber;
            person.EMail = editedPlayers.EMail;
            person.IsPlayer = editedPlayers.IsPlayer;
            person.IsCoach = editedPlayers.IsCoach;
            person.IsValid = editedPlayers.IsValid;
            person.IsAdmin = editedPlayers.IsAdmin;
            person.TeamId = editedPlayers.TeamId;
            personManager.Update(person);

            return RedirectToAction("PlayerIndex");
        }

        #endregion

        #region ViewTeamPlayers
        public async Task<ActionResult> ViewTeamPlayers(int Id)
        {
            var players = await GetPlayersInTeamAsync(Id);

            return View(players);
        }
        #endregion

    }
}

WhosOnFirstWeb/Views/Player/EditPlayer.cshtml
@model WhosOnFirstWeb.Models.PlayersModel
@{
    ViewBag.Title = "EditPlayer";
}
<h2>Edit My Profile</h2>
<br />
<ul>
    <li>
        @using (Html.BeginForm("EditPlayer", "Player", FormMethod.Post))
        {
            @Html.HiddenFor(m => m.PersonId, new { @Value = Model.PersonId })
            @Html.HiddenFor(m => m.PlayerId, new { @Value = Model.PlayerId })
            @Html.HiddenFor(m => m.IsPlayer, new { @Value = Model.IsPlayer })
            @Html.HiddenFor(m => m.IsCoach, new { @Value = Model.IsCoach })
            @Html.HiddenFor(m => m.IsAdmin, new { @Value = Model.IsAdmin })
            @Html.HiddenFor(m => m.IsValid, new { @Value = Model.IsValid })
            @Html.HiddenFor(m => m.IsPitcher, new { @Value = Model.IsPitcher })
            @Html.HiddenFor(m => m.TeamId, new { @Value = Model.TeamId })

            <div class="form-group">
                @Html.Label("First Name")
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.FirstName })
            </div>
            <div class="form-group">
                @Html.Label("Last Name")
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.LastName })
            </div>
            <div class="form-group">
                @Html.Label("E-mail Address")
                @Html.TextBoxFor(m => m.EMail, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.EMail })
            </div>
            <div class="form-group">
                @Html.Label("Phone Number")
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.PhoneNumber })
            </div>
            <div class="form-group">
                @Html.Label("Position Requested")
                @Html.TextBoxFor(m => m.PositionRequested, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.PositionRequested })
            </div>
            <div class="form-group">
                @Html.Label("Team Requested")
                @Html.TextBoxFor(m => m.TeamRequested, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.TeamRequested })
            </div>
            <div class="form-group">
                @Html.Label("Note")
                @Html.TextAreaFor(m => m.Note, new { @class = "form-control", autofocus = "autofocus", @Value = @Model.Note, rows = "5", cols = "20" })
            </div>

            <br />
            <input type="submit" class="btn btn-primary" name="Submit" />
        }
    </li>
</ul>

WhosOnFirstWeb/Views/Player/PlayerIndex.cshtml
@model WhosOnFirstWeb.Models.PlayersModel
@{
    ViewBag.Title = "PlayerIndex";
}

<div class="form-group">
    <h1>Welcome @Model.UserModel.LastName!</h1>
</div>
<br/>
<div class="form-group">
    <div>
        <label style="font-size: 20px">@Model.FirstName @Model.LastName</label>
        <label>&nbsp;&nbsp;Phone Number:  @Model.PhoneNumber</label>
        <label>&nbsp;&nbsp;e-mail:  @Model.EMail</label>
        <label>&nbsp;&nbsp;Jersey Number:  @Model.JerseyNumber</label>
    </div>
    <div>
        <label>Position Requested:  @Model.PositionRequested</label>
        <label>&nbsp;&nbsp;Team Requested:  @Model.TeamRequested</label>
    </div>
    <div>

        <label>Note:  @Model.Note</label>
    </div>
</div>
<div class="form-group">
    <button class="btn btn-primary btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("EditPlayer","Player")'">Edit</button>
    <button class="btn btn-danger btn-sm" style="margin-left: 20px" onclick="location.href='@Url.Action("ViewTeamPlayers","Player", new {Id = @Model.TeamId})'">View Team</button>
</div>

WhosOnFirstWeb/Views/Player/ViewTeamPlayers.cshtml
@{
    ViewBag.Title = "ViewTeamPlayers";
}

<h1>Players on team</h1>
<br />
<div>
    @foreach (var player in Model)
    {
        <div class="form-group">
            <div>
                <label style="font-size: 20px">@player.FirstName @player.LastName</label>
                <label>&nbsp;&nbsp;Phone Number:  @player.PhoneNumber</label>
                <label>&nbsp;&nbsp;e-mail:  @player.EMail</label>
                <label>&nbsp;&nbsp;Jersey Number:  @player.JerseyNumber</label>
            </div>
            <div>
                <label>Position Requested:  @player.PositionRequested</label>
                <label>&nbsp;&nbsp;Team Requested:  @player.TeamRequested</label>
            </div>
            <div>

                <label>Note:  @player.Note</label>
            </div>
        </div>
        <div style="clear: both;"></div>
    }
</div>
<br />

<form action="~/Player/PlayerIndex">
    <button class="btn btn-primary">Back</button>
</form>